# Generated by Django 5.2.6 on 2025-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_customer_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="total_amount",
            new_name="cgst_amount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="cgst_percentage",
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="invoice",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sgst_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sgst_percentage",
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="taxable_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
