# Generated by Django 5.2.6 on 2025-10-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_customorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
